# Generated by Django 4.2.18 on 2025-02-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0003_category_alter_contribution_borrower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanprofile",
            name="story",
            field=models.TextField(
                blank=True,
                help_text="A short description of the user and their reason why.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loanprofile",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="loan_profiles", to="loan.category"
            ),
        ),
        migrations.AlterField(
            model_name="loanprofile",
            name="description",
            field=models.TextField(
                blank=True, help_text="The description of the loan profile.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loanprofile",
            name="loan_duration",
            field=models.IntegerField(
                blank=True,
                default=12,
                help_text="The duration of the loan in months.",
                null=True,
            ),
        ),
    ]
