# Generated by Django 4.2.18 on 2025-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0004_loanprofile_story_alter_loanprofile_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanprofile",
            name="profile_img",
            field=models.URLField(
                blank=True,
                help_text="The URL of the photo for the loan profile.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loanprofile",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title of the loan profile.",
                max_length=255,
                null=True,
            ),
        ),
    ]
