# Generated by Django 4.2.18 on 2025-02-11 06:12

import loan.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0005_alter_loanprofile_profile_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanprofile",
            name="deadline_to_receive_loan",
            field=models.DateField(
                default=loan.utils.one_year_from_now_date,
                help_text="The deadline to receive the loan.",
            ),
        ),
    ]
