# Generated by Django 4.2.18 on 2025-02-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0006_alter_loanprofile_deadline_to_receive_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loanprofile",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
