# Generated by Django 4.2.18 on 2025-04-12 06:06

import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(2.5, 'USD'))]),
        ),
    ]
