# Generated by Django 4.2.18 on 2025-02-05 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
