# Generated by Django 4.2.18 on 2025-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                help_text="Profile image url for the user.",
                null=True,
                upload_to="user_images/",
            ),
        ),
    ]
