# Generated by Django 4.2.18 on 2025-04-02 03:58

import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0.01, 'USD'))]),
        ),
    ]
