# Generated by Django 3.2.25 on 2024-11-03 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loanprofile_deadline_to_receive_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Walter', help_text='The first name of the user.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='White', help_text='The last name of the user.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 11, 3, 19, 47, 20, 330028, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='The interests of the user.'),
        ),
    ]
