# Generated by Django 3.2.25 on 2024-10-18 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loanprofile_deadline_to_receive_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 10, 18, 20, 12, 53, 4098, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
    ]
