# Generated by Django 3.2.25 on 2024-11-21 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241104_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 11, 21, 21, 0, 40, 439452, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
    ]
