# Generated by Django 3.2.25 on 2024-11-22 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_loanprofile_deadline_to_receive_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 11, 22, 5, 26, 51, 618150, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
    ]
