# Generated by Django 3.2.25 on 2024-12-24 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20241218_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', help_text='The first name of the user.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', help_text='The last name of the user.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 12, 24, 9, 39, 3, 773007, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
    ]
