# Generated by Django 3.2.25 on 2024-11-23 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hordak', '0041_auto_20240528_2107'),
        ('transaction', '0002_alter_transaction_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('platform', models.CharField(choices=[('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('OTHER', 'Other')], default='PAYPAL', help_text='The external payment platform used.', max_length=20)),
                ('gateway_payment_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the payment in USD.', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='The status of the payment.', max_length=20)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_payment', to='hordak.transaction')),
                ('user', models.ForeignKey(help_text='The user who initiated the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='external_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Payment',
                'verbose_name_plural': 'External Payments',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
