# Generated by Django 3.2.25 on 2024-11-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0041_auto_20240528_2107'),
        ('transaction', '0003_auto_20241123_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_payment', to='hordak.transaction'),
        ),
    ]
